accounts/urls.py
from django.urls import path
from accounts.views import UserRegister, ProfileUpdateView, UserDeleteView

app_name = "accounts"

urlpatterns = [
    path('register/', UserRegister.as_view(), name="register"),
    path('user-profil/<str:user>/', ProfileUpdateView, name='profile_update'),
    path('user-delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
]

article/urls.py
from django.urls import path

from .views import ArticleListView, ArticleDetailView, ArticleCategoryView, ArticleTagsView

app_name = 'article'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article_home'),
    path('<int:pk>/<str:category>/<str:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<str:category>/', ArticleCategoryView.as_view(), name='article_category'),
    path('etiketler/<tags>/', ArticleTagsView.as_view(), name='article_tags'),
]

ecommerce/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_ckeditor_5.views import upload_file
from article.views import post_likes, post_dislikes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("ckeditor5_upload_file/", upload_file, name="ckeditor5_upload_file"),
    path('', include('store.urls', namespace='store')),
    path("gallery-handler/", include("galleryfield.urls")),
    path('makale/', include('article.urls', namespace='article')),
    path('post-likes/<int:pk>/', post_likes, name='post_likes'),
    path('post-dislikes/<int:pk>/', post_dislikes, name='post_dislikes'),
    path('accounts/', include('accounts.urls', namespace="accounts")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

admin.site.site_title = "E-Commerce"

admin.site.site_header = "E-Commerce Admin Panel"

store/urls.py
from django.urls import path
from .views import (
    StoreListView, ProductDetailView, ProductCategoryView, product_likes, product_dislikes, wish_list, \
    SortByLowPriceView, SortByHighPriceView, NewestProductsView, comment_delete, report_comment,
    MostLikesProductsView, BrandCategoryView, add_cart, MyCartView, UpdateMyCart, remove_product_from_cart,
    MostViewedProductsView, checkout_view, PromoCodeView, valid_cart, non_valid_cart, add_non_valid_my_cart,
    remove_non_valid_my_cart, SubscribeView, unsubscribe, contact, WishListView, remove_item_wishlist, DiscountProductsView
)

app_name = 'store'

urlpatterns = [
    path('', StoreListView.as_view(), name='store_home'),
    path('<int:pk>/<str:brand>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('product-kategori/<str:category>/', ProductCategoryView.as_view(), name='product_category'),
    path('product-marka-kategori/<str:brand>/', BrandCategoryView.as_view(), name='brand_category'),
    path('like/<pk>/', product_likes, name='product_likes'),
    path('dislike/<pk>/', product_dislikes, name='product_dislikes'),
    path('add-wish-list/<pk>/', wish_list, name='wish_list'),
    path('sırala/düsuk-fiyattan-yüksek-fiyata/', SortByLowPriceView.as_view(), name='sort_low_price'),
    path('sırala/yüksek-fiyattan-düşük-fiyata/', SortByHighPriceView.as_view(), name='sort_high_price'),
    path('sırala/en-çok-begenilen-ürünler/', MostLikesProductsView.as_view(), name='most_likes_products'),
    path('sırala/yeni-gelenden-eskiye/', NewestProductsView.as_view(), name='newest_products'),
    path('sırala/most-viewed-products/', MostViewedProductsView.as_view(), name='most_viewed_products'),
    path('sırala/indirimli-ürünler/', DiscountProductsView.as_view(), name='dicount_products'),
    path('comment-delete/<pk>/', comment_delete, name='comment_delete'),
    path('report/<pk>/', report_comment, name='report_comment'),
    path('add-cart/<pk>/<cart_id>/', add_cart, name='add_cart'),
    path('sepetim/<user>/<cart_id>/', MyCartView, name='my_cart_list'),
    path('update-my-cart/<int:pk>/', UpdateMyCart, name='update_my_cart'),
    path('valid_my_cart/<cart_id>/', valid_cart, name='valid_my_cart'),
    path('non_valid_cart/<cart_id>/', non_valid_cart, name='non_valid_cart'),
    path('add_non_valid_my_cart/<pk>/<cart_id>/', add_non_valid_my_cart, name='add_non_valid_my_cart'),
    path('remove_non_valid_my_cart/<pk>/<cart_id>/', remove_non_valid_my_cart, name='remove_non_valid_my_cart'),
    path('remove_product_from_cart/<int:pk>/', remove_product_from_cart, name='remove_product_from_cart'),
    path('checkout-cart/<user>/<cart_id>/', checkout_view, name='checkout_view'),
    path('promo-code/<user>/<cart_id>/', PromoCodeView, name='promo_code'),
    path('abone-ol/', SubscribeView, name='abone_ol'),
    path('unsubscribe/<unsubscribe_email>/', unsubscribe, name='unsubscribe'),
    path('iletişim/', contact, name='contact'),
    path('istek-listem/<user>/', WishListView, name='my_wish_list'),
    path('istek-listesinden-çıkart/<pk>/', remove_item_wishlist, name='remove_wish_list'),
]

templates/pages/article_detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% load thumbnail %}
{% load hitcount_tags %}
{% load meta_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block meta_tags %}
	<meta name="description" content="{{ post.title }}">
    <meta name="keywords" content="{{ request.get_host }},{{ post.category.title }},{{ post.slug|rsplit_keywords }}">
    <meta name="author" content="{{ post.author }}">
    <meta property="og:title" content="{{ post.title }}" />
    <meta property="og:description" content="{{ post.description }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{{ post.cover.url }}" />
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="tr" />
    <meta property="article:author" content="{{ post.author }}" />
    <link rel="canonical" href="{{ post.cover.url }}">
{% endblock %}

{% block content %}
    <main class="container">

        <section class="section section bg-soft pb-5 overflow-hidden z-2">
            <div class="container z-2">
                <div class="row justify-content-center text-center pt-6">
                    <div class="col-lg-12 col-xl-12">
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <div class="alert alert-danger alert-dismissible shadow-soft fade show mt-5"
                                         role="alert">
                                {% else %}
                                    <div class="alert alert-{{ message.tags }} alert-dismissible shadow-soft fade show"
                                         role="alert">
                                {% endif %}

                            <span class="alert-inner--icon">
                                    {% if message.tags == 'error' %}
                                        <span class="far fa-thumbs-down"></span>
                                    {% elif message.tags == 'success' %}
                                        <span class="far fa-thumbs-up"></span>
                                    {% else %}

                                    {% endif %}
                                </span>

                            <span class="alert-inner--text"><strong>{{ message }}</strong> </span>

                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            {% endfor %}
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">

                </h3>

                <article class="blog-post">
                    <h2 class="display-5 link-body-emphasis mb-1" style="text-align: justify">{{ post.title }}</h2>
                    <div class="card-body pt-2">

                    </div>

                    <div id="blueimp-gallery-carousel"
                         class="blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel rounded border-light shadow-soft"
                         aria-label="image carousel">

                        <div class="slides" aria-live="off"></div>
                        <h3 class="title"></h3>
                        <a class="prev" aria-controls="blueimp-gallery-carousel" aria-label="previous slide"></a>
                        <a class="next" aria-controls="blueimp-gallery-carousel" aria-label="next slide"></a>
                        <a class="play-pause" aria-controls="blueimp-gallery-carousel"
                           aria-label="play slideshow"
                           aria-pressed="true"
                           role="button"></a>

                        <ol class="indicator"></ol>

                    </div>

                    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
                        <div class="slides"></div>
                        <h3 class="title"></h3>
                        <a class="prev"></a>
                        <a class="next"></a>
                        <a class="close"></a>
                        <a class="play-pause"></a>
                        <ol class="indicator"></ol>
                    </div>

                    <div id="links">

                        {% if post.cover.url and post.article_images.count == 0 %}

                            <a href="{{ post.cover.url }}" class="ml-2 text-decoration-none" data-gallery="identifier">
                                <img src="{{ post.cover.url }}" width="50" height="50"
                                     alt="{{ post.cover.name }}"/>
                            </a>

                        {% else %}

                            {% for foo in post.article_images.all %}
                                {% if foo.images %}
                                    <a href="{{ foo.images.url }}" class="ml-2 text-decoration-none"
                                       data-gallery="identifier">
                                        <img src="{{ foo.images.url }}" width="50" height="50"
                                             alt="{{ foo.images.name }}"/>
                                    </a>
                                {% endif %}
                            {% endfor %}

                        {% endif %}
                    </div>

                    <hr>

                    <div class="media d-flex align-items-center justify-content-between">

                        <div class="d-flex align-items-center">
                            <a href="{% url 'article:article_category' post.category.title|slugify %}">
                                    <span class="small" title="Kategori" data-toggle="tooltip">
                                    <span class="badge badge-danger">{{ post.category.title|title }}</span>
                                </span>
                            </a>

                        </div>

                        <div class="d-flex align-items-center">
                                <span class="small" title="Yayınlanma tarihi" data-toggle="tooltip">
                                    <span class="far fa-calendar-alt mr-1"></span>
                                    <span class="badge badge-info">{{ post.created.date }}</span>
                                </span>
                        </div>

                    </div>


                    <div class="float-left mt-4">
                        <a href="{% url 'post_likes' post.pk %}"
                           class="btn-inner-icon mt-3 ml-1 text-decoration-none">
                                            <span class="mr-1">
                                                <span class="fas fa-thumbs-up text-success fa-2x animate-up-2"
                                                      data-toggle="tooltip"
                                                      title="Makaleyi Beğendim"></span>
                                                <span class="badge badge-success" data-toggle="tooltip"
                                                      title="Makaleyi {{ post.likes.count }} kişi beğendi">{{ post.likes.count }}</span>
                                            </span>
                        </a>
                        <a href="{% url 'post_dislikes' post.pk %}"
                           class="btn-icon mt-3 ml-3 text-decoration-none">
                                            <span class="mr-1">
                                                <span class="fas fa-thumbs-down text-danger fa-2x animate-down-2"
                                                      data-toggle="tooltip"
                                                      title="Makaleyi Beğenmedim"></span>
                                                <span class="badge badge-danger" data-toggle="tooltip"
                                                      title="Bu ürünü {{ post.dislikes.count }} kişi beğenmedi">{{ post.dislikes.count }}</span>
                                                
                                            </span>
                        </a>
                    </div>

                    <div class="float-right mt-5">
                        <a href="#"
                           class="btn-inner-icon mt-3 ml-1 text-decoration-none">
                            <span class="mr-1" data-toggle="tooltip"
                                  title="{% get_hit_count for post %} kişi görüntüledi">
                                                <span class="fas fa-eye text-info"></span>
                                                <span class="badge badge-success">
                                                    {% get_hit_count for post %}
                                                </span>
                            </span>
                        </a>

                    </div>

                    <hr>

                    <div class="mt-6">{{ post.text|safe }}</div>

                </article>

            </div>

            <div class="col-md-4">

                <div class="position-sticky" style="top: 2rem;">

                    <div class="p-4 mb-3 bg-body-tertiary rounded">
                        <h4 class="fst-italic">Paylaş</h4>
                        <p class="mb-0 text-justify" style="text-align: justify">
                            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                                <button class="btn btn-icon-only btn-pill btn-facebook mr-2" type="button"
                                        aria-label="facebook button" title="facebookda paylaş">
                                    <span aria-hidden="true" class="fab fa-facebook"></span>
                                </button>
                            </a>

                            <a href="https://twitter.com/intent/tweet?text={{ request.build_absolute_uri }}">
                                <button class="btn btn-icon-only btn-pill btn-twitter mr-2" type="button"
                                        aria-label="twitter button" title="twitterda paylaş">
                                    <span aria-hidden="true" class="fab fa-twitter"></span>
                                </button>
                            </a>
                            <a href="https://api.whatsapp.com/send?text={{ request.build_absolute_uri }}">
                                <button class="btn btn-icon-only btn-pill btn-instagram text-success mr-2"
                                        type="button"
                                        aria-label="whatsapp button" title="whatsappda paylaş">
                                    <span aria-hidden="true" class="fab fa-whatsapp"></span>
                                </button>
                            </a>
                            <a href="https://www.linkedin.com/cws/share/?url={{ request.build_absolute_uri }}">
                                <button class="btn btn-icon-only btn-pill btn-instagram text-info" type="button"
                                        aria-label="linkedin button" title="linkedinda paylaş">
                                    <span aria-hidden="true" class="fab fa-linkedin-in"></span>
                                </button>
                            </a>
                        </p>
                    </div>

                    <div class="p-4">
                        <h4 class="fst-italic">İlişkili gönderiler</h4>
                        <ul class="list-unstyled">
                            {% for related_post in related_posts %}
                                <li>
                                    <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis  border-top"
                                       href="{% url 'article:article_detail' post.pk post.category.title|slugify post.slug %}">
                                        <div class="col-lg-12">
                                            <h6 class="mb-0 small font-weight-bold">{{ related_post.title }}</h6>
                                            <small class="text-body-secondary">{{ related_post.created.date }}</small>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>



                    <div class="p-4 mb-3 bg-body-tertiary rounded">
                        <h4 class="fst-italic border-bottom mb-2">Etiketler</h4>
                        {% for article_tag in article_tags %}
                            <a class="btn-pill btn-google-plus btn-sm mb-3 mr-1 mt-4 text-italic"
                               href="{% url 'article:article_tags' article_tag.tags %}">#{{ article_tag.tags|title }}</a>
                        {% endfor %}

                    </div>

                </div>
            </div>
        </div>

    </main>
{% endblock %}

templates/pages/contact_email.html
{% load i18n %}

<!doctype html>
<html lang="en-GB" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
{% autoescape off %}

    <div>{% translate "Konu:" %} {% blocktranslate %}{{ subject }}{% endblocktranslate %}</div>

    <div>{% translate 'Ad-Soyad:' %} {{ name }}</div>

    <div>{% translate "Mesaj:" %} {% blocktranslate %}{{ message }}{% endblocktranslate %}</div>

    <div>{% translate 'İletişim Mail:' %} {{ email }}</div>

{% endautoescape %}
</body>
</html>

templates/pages/my_cart.html
{% extends 'layout/base.html' %}
{% load static %}
{% load thumbnail %}
{% load hitcount_tags %}
{% block title %} Alışveriş Sepetim {% endblock %}

{% block content %}

    <main class="container p-5" style="margin-top: 10%">

        <div class="row justify-content-center text-center pt-3">

            <div class="col-lg-12 col-xl-12 " style="margin-top: -11%">
                <h1 class="display-2 mb-2">
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <div class="alert alert-danger alert-dismissible shadow-soft fade show"
                                     role="alert">
                            {% else %}
                                <div class="alert alert-{{ message.tags }} alert-dismissible shadow-soft fade show"
                                     role="alert">
                            {% endif %}

                        <span class="alert-inner--icon">
                                        {% if message.tags == 'error' %}
                                            <span class="far fa-thumbs-down"></span>
                                        {% elif message.tags == 'success' %}
                                            <span class="far fa-thumbs-up"></span>
                                        {% else %}

                                        {% endif %}
                                    </span>

                        <span class="alert-inner--text"><strong>{{ message }}</strong> </span>

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        {% endfor %}
                    {% endif %}

                    </div>

                </h1>
            </div>

            <div class="row g-5">

                <div class="col-md-12">

                    <div class="pb-3 mb-2">
                        <div class="pb-2 border-bottom mt-4" style="margin-right: -10px">
                            {% if my_cart_list %}
                                <span class="h4">Sepetim
                                    <i class="badge badge-info badge-md h2">{{ cart_total_products }}</i>
                            </span>
                            {% else %}
                                <span class="h4">Sepetim</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row">
                        {% if valid_cart_list %}
                            <table class="table table-responsive shadow-soft rounded">
                                <tr>
                                    <th class="border-0" scope="col" id="class">Ürün Kodu</th>
                                    <th class="border-0" scope="col" id="teacher">Ürün</th>
                                    <th class="border-0" scope="col" id="teacher">Birim Fiyat</th>
                                    <th class="border-0" scope="col" id="males">Adet</th>
                                    <th class="border-0" scope="col" id="females">Tutar</th>
                                </tr>
                                {% if my_cart_list %}
                                    {% for my_cart in my_cart_list %}
                                        <tr>

                                            <td>{{ my_cart.product.product_code }}</td>

                                            <th>
                                                <a href="{% url "store:product_detail" my_cart.product.pk my_cart.product.brand|slugify my_cart.product.slug %}"
                                                   title="Ürüne git" data-toggle="tooltip">
                                                    {{ my_cart.product.title }}
                                                </a>
                                            </th>

                                            {% if my_cart.product.discount %}
                                                <td>{{ my_cart.product.discount_price }}</td>
                                            {% else %}
                                                <td>{{ my_cart.product.price }}</td>
                                            {% endif %}

                                            <td class="table-responsive">{{ my_cart.quantity }}</td>

                                            <td>{{ my_cart.items_total }}</td>

                                        <tr>
                                    {% endfor %}

                                {% endif %}

                                <tr class="font-weight-bold">
                                    <td>Toplam:</td>
                                    <td></td>
                                    <td></td>
                                    <td>{{ cart_total_products }}</td>
                                    <td><p class="badge badge-soft text-info">{{ cart_total_price }} TL</p></td>
                                </tr>

                            </table>
                        {% else %}
                            {% if my_cart_list %}
                                <table class="table table-responsive shadow-soft rounded">
                                    <tr>
                                        <th class="border-0" scope="col" id="class">Ürün Kodu</th>
                                        <th class="border-0" scope="col" id="teacher">Ürün</th>
                                        <th class="border-0" scope="col" id="teacher">Birim Fiyat</th>
                                        <th class="border-0" scope="col" id="males">Adet</th>
                                        <th class="border-0" scope="col" id="females">Tutar</th>
                                        <th class="border-0" scope="col" id="females">İşlem</th>
                                    </tr>
                                    {% if my_cart_list %}
                                        {% for my_cart in my_cart_list %}
                                            <tr>
                                                <td>{{ my_cart.product.product_code }}</td>
                                                <th>
                                                    <a href="{% url "store:product_detail" my_cart.product.pk my_cart.product.brand|slugify my_cart.product.slug %}"
                                                       title="Ürüne git" data-toggle="tooltip">
                                                        {{ my_cart.product.title }}
                                                    </a>
                                                </th>

                                                {% if my_cart.product.discount %}
                                                    <td>{{ my_cart.product.discount_price }}</td>
                                                {% else %}
                                                    <td>{{ my_cart.product.price }}</td>
                                                {% endif %}

                                                <td class="table-responsive">{{ my_cart.quantity }}</td>

                                                <td>{{ my_cart.items_total }}</td>

                                                <td>
                                                    <a href="{% url "store:add_non_valid_my_cart" my_cart.product.pk cart_id %}"
                                                       style="margin-left: -9%">
                                                        <button class="btn btn-primary btn-sm ml-2" title="Ekle"
                                                                data-toggle="tooltip">
                                                            <i class="fa fa-arrow-up text-success animate-up-3"></i>
                                                        </button>
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{% url "store:remove_non_valid_my_cart" my_cart.product.pk cart_id %}">
                                                        <button class="btn btn-primary btn-sm " title="Çıkart"
                                                                data-toggle="tooltip">
                                                            <i class="fa fa-arrow-down text-danger animate-down-3"
                                                               title="Çıkart"></i>
                                                        </button>
                                                    </a>
                                                </td>

                                                <td>
                                                    <a href="{% url "store:remove_product_from_cart" my_cart.product.pk %}">
                                                        <button class="btn btn-primary btn-sm ml-2"
                                                                title="Sepetten Çıkar"
                                                                data-toggle="tooltip">
                                                            <i class="fa fa-trash text-danger"></i>
                                                        </button>
                                                    </a>
                                                </td>

                                            <tr>
                                        {% endfor %}

                                    {% endif %}

                                    <tr class="font-weight-bold">
                                        <td>Toplam:</td>
                                        <td></td>
                                        <td></td>
                                        <td>{{ cart_total_products }}</td>
                                        <td><p class="badge badge-soft text-info">{{ cart_total_price }} TL</p></td>
                                    </tr>
                                </table>
                            {% else %}
                                <p class="mx-auto text-danger h4">Sepet Boş</p>
                            {% endif %}

                        {% endif %}
                    </div>

                    {% if valid_cart_list %}
                        <a href="{% url "store:non_valid_cart" cart_id %}" style="float: left; margin-left: -10px">
                            <button class="btn btn-primary" style="float: right; margin-right: -10px"><i
                                    class="fa fa-edit text-warning mr-2"></i>Düzenle
                            </button>
                        </a>

                        <a href="{% url "store:checkout_view" request.user cart_id %}">
                            <button class="btn btn-primary" style="float: right; margin-right: -10px"><i
                                    class="fa fa-shopping-cart text-info mr-2"></i>Ödeme Yap
                            </button>
                        </a>
                    {% else %}
                        {% if my_cart_list %}
                            <form action="{% url "store:valid_my_cart" cart_id %}">
                                <button class="btn btn-primary" style="float: right; margin-right: -10px" type="submit">
                                    <i class="fa fa-thumbs-up text-success mr-2"></i>Sepeti
                                    onayla
                                </button>
                            </form>
                        {% endif %}
                    {% endif %}

                </div>
            </div>
        </div>
    </main>

{% endblock %}