article/urls.py
from django.urls import path

from .views import ArticleListView, ArticleDetailView, ArticleCategoryView, ArticleTagsView

app_name = 'article'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article_home'),
    path('<int:pk>/<str:category>/<str:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<str:category>/', ArticleCategoryView.as_view(), name='article_category'),
    path('etiketler/<tags>/', ArticleTagsView.as_view(), name='article_tags'),
]

ecommerce/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_ckeditor_5.views import upload_file
from article.views import post_likes, post_dislikes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("ckeditor5_upload_file/", upload_file, name="ckeditor5_upload_file"),
    path('', include('store.urls', namespace='store')),
    path("gallery-handler/", include("galleryfield.urls")),
    path('makale/', include('article.urls', namespace='article')),
    path('post-likes/<int:pk>/', post_likes, name='post_likes'),
    path('post-dislikes/<int:pk>/', post_dislikes, name='post_dislikes'),
    path('accounts/', include('accounts.urls', namespace="accounts")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

admin.site.site_title = "E-Commerce"

admin.site.site_header = "E-Commerce Admin Panel"

store/urls.py
from django.urls import path
from .views import (
    StoreListView, ProductDetailView, ProductCategoryView, product_likes, product_dislikes, wish_list, \
    SortByLowPriceView, SortByHighPriceView, NewestProductsView, comment_delete, report_comment,
    MostLikesProductsView, BrandCategoryView, add_cart, MyCartView, UpdateMyCart, remove_product_from_cart,
    MostViewedProductsView, checkout_view, PromoCodeView, valid_cart, non_valid_cart, add_non_valid_my_cart,
    remove_non_valid_my_cart, SubscribeView, unsubscribe, contact, WishListView, remove_item_wishlist, DiscountProductsView
)

app_name = 'store'

urlpatterns = [
    path('', StoreListView.as_view(), name='store_home'),
    path('<int:pk>/<str:brand>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('product-kategori/<str:category>/', ProductCategoryView.as_view(), name='product_category'),
    path('product-marka-kategori/<str:brand>/', BrandCategoryView.as_view(), name='brand_category'),
    path('like/<pk>/', product_likes, name='product_likes'),
    path('dislike/<pk>/', product_dislikes, name='product_dislikes'),
    path('add-wish-list/<pk>/', wish_list, name='wish_list'),
    path('sırala/düsuk-fiyattan-yüksek-fiyata/', SortByLowPriceView.as_view(), name='sort_low_price'),
    path('sırala/yüksek-fiyattan-düşük-fiyata/', SortByHighPriceView.as_view(), name='sort_high_price'),
    path('sırala/en-çok-begenilen-ürünler/', MostLikesProductsView.as_view(), name='most_likes_products'),
    path('sırala/yeni-gelenden-eskiye/', NewestProductsView.as_view(), name='newest_products'),
    path('sırala/most-viewed-products/', MostViewedProductsView.as_view(), name='most_viewed_products'),
    path('sırala/indirimli-ürünler/', DiscountProductsView.as_view(), name='dicount_products'),
    path('comment-delete/<pk>/', comment_delete, name='comment_delete'),
    path('report/<pk>/', report_comment, name='report_comment'),
    path('add-cart/<pk>/<cart_id>/', add_cart, name='add_cart'),
    path('sepetim/<user>/<cart_id>/', MyCartView, name='my_cart_list'),
    path('update-my-cart/<int:pk>/', UpdateMyCart, name='update_my_cart'),
    path('valid_my_cart/<cart_id>/', valid_cart, name='valid_my_cart'),
    path('non_valid_cart/<cart_id>/', non_valid_cart, name='non_valid_cart'),
    path('add_non_valid_my_cart/<pk>/<cart_id>/', add_non_valid_my_cart, name='add_non_valid_my_cart'),
    path('remove_non_valid_my_cart/<pk>/<cart_id>/', remove_non_valid_my_cart, name='remove_non_valid_my_cart'),
    path('remove_product_from_cart/<int:pk>/', remove_product_from_cart, name='remove_product_from_cart'),
    path('checkout-cart/<user>/<cart_id>/', checkout_view, name='checkout_view'),
    path('promo-code/<user>/<cart_id>/', PromoCodeView, name='promo_code'),
    path('abone-ol/', SubscribeView, name='abone_ol'),
    path('unsubscribe/<unsubscribe_email>/', unsubscribe, name='unsubscribe'),
    path('iletişim/', contact, name='contact'),
    path('istek-listem/<user>/', WishListView, name='my_wish_list'),
    path('istek-listesinden-çıkart/<pk>/', remove_item_wishlist, name='remove_wish_list'),
]

templates/include/examples_cards.html
{% load static %}
<div class="col-12 col-md-4">
    <div class="card bg-primary border-light shadow-soft">
        <div class="card-header p-3">
            <img src="{% static 'img/blog-article-1.jpg' %}" class="card-img-top rounded"
                 alt="Designer desk">
        </div>
        <div class="card-body pt-2">
            <div class="media d-flex align-items-center justify-content-between">
                <div class="post-group">
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                       data-original-title="23k followers">
                        <img class="avatar-sm mr-2 img-fluid rounded-circle"
                             src="{% static 'img/profile-picture-1.jpg' %}" alt="Jo portrait">
                        Jo
                        J. Moore
                    </a>
                </div>
                <div class="d-flex align-items-center">
                    <span class="small"><span class="far fa-calendar-alt mr-2"></span>15 March 2020</span>
                </div>
            </div>
            <h3 class="h5 card-title mt-4">We partnered up with Google</h3>
            <p class="card-text">Some quick example text to build on the card title and make up
                the
                bulk of the card's content.</p>
            <a href="#" class="btn btn-primary btn-sm">Learn More</a>
        </div>
    </div>
</div>

<div class="col-12 col-md-4">
    <div class="card bg-primary border-light shadow-soft">
        <div class="card-header p-3">
            <img src="{% static 'img/blog-article-2.jpg' %}" class="card-img-top rounded"
                 alt="Designer desk">
        </div>
        <div class="card-body pt-2">
            <div class="media d-flex align-items-center justify-content-between">
                <div class="post-group">
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                       data-original-title="23k followers">
                        <img class="avatar-sm mr-2 img-fluid rounded-circle"
                             src="{% static 'img/profile-picture-2.jpg' %}" alt="Jo portrait">
                        Jo
                        J. Moore
                    </a>
                </div>
                <div class="d-flex align-items-center">
                    <span class="small"><span class="far fa-calendar-alt mr-2"></span>15 March 2020</span>
                </div>
            </div>
            <h3 class="h5 card-title mt-4">We partnered up with Google</h3>
            <p class="card-text">Some quick example text to build on the card title and make up
                the
                bulk of the card's content.</p>
            <a href="#" class="btn btn-primary btn-sm">Learn More</a>
        </div>
    </div>
</div>

templates/include/footer.html
{% load static %}
{% load general_settings %}
{% neuromorphism_general_settings as neuromorphism_general_settings %}
<footer class="d-flex pb-5 pt-6 pt-md-7 border-top border-light bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <p><strong>{% if neuromorphism_general_settings.name %}
                    {{ neuromorphism_general_settings.name|title }}{% else %}
                    Neuromorphism{% endif %}</strong> {{ neuromorphism_general_settings.explain }}</p>
                <ul class="d-flex list-unstyled mb-5 mb-lg-0">
                    <li class="mr-2">
                        <a href="https://twitter.com/themesberg" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="twitter social link"
                           data-toggle="tooltip" data-placement="top" title="Follow @themesberg on Twitter">
                            <span aria-hidden="true" class="fab fa-twitter"></span>
                        </a>
                    </li>
                    <li class="mr-2">
                        <a href="https://www.facebook.com/themesberg/" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="facebook social link"
                           data-toggle="tooltip" data-placement="top" title="Like @themesberg on Facebook">
                            <span aria-hidden="true" class="fab fa-facebook"></span>
                        </a>
                    </li>
                    <li class="mr-2">
                        <a href="https://github.com/themesberg" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="github social link"
                           data-toggle="tooltip" data-placement="top" title="Open source projects">
                            <span aria-hidden="true" class="fab fa-github"></span>
                        </a>
                    </li>
                    <li>
                        <a href="https://dribbble.com/themesberg" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="dribbble social link"
                           data-toggle="tooltip" data-placement="top" title="Follow us on Dribbble">
                            <span aria-hidden="true" class="fab fa-dribbble"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-lg-2 mb-5 mb-lg-0">
                <h5>{% if neuromorphism_general_settings.name %}
                    {{ neuromorphism_general_settings.name|title }}{% else %}Themesberg{% endif %}</h5>
                <ul class="footer-links list-unstyled mt-2">
                    <li class="mb-1"><a class="p-2" target="_blank" href="{% url 'store:store_home' %}">Mağaza</a></li>
                    <li class="mb-1"><a class="p-2" target="_blank" href="{% url 'article:article_home' %}">Makale</a>
                    </li>
                    <li class="mb-1"><a class="p-2" target="_blank" href="#">Hakkımızda</a></li>
                    <li><a class="p-2" target="_blank" href="{% url 'store:contact' %}">İletişim</a></li>
                </ul>
            </div>
            <div class="col-6 col-lg-2 mb-5 mb-lg-0">
                <h5>Diğer</h5>
                <ul class="footer-links list-unstyled mt-2">

                    <li class="mb-1">
                        <a class="p-2" href="https://themesberg.com/docs/pixel-bootstrap/getting-started/changelog"
                           target="_blank">Sıkça sorulan sorular</a>
                    </li>
                    <li class="mb-1">
                        <a class="p-2" target="_blank" href="https://themesberg.com/licensing">Lisans</a>
                    </li>
                    <li>
                        <a class="p-2" target="_blank"
                           href="https://github.com/themesberg/pixel-bootstrap-ui-kit/issues">Gizlilik ilkemiz</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-4 mb-5 mb-lg-0">
                <h5>Abonelik</h5>
                <p class="text-gray font-small mt-2">Bültenimize abone olun ve ürünlerimiz ve hizmetlerimizle ilgili en
                    son haberleri alın!</p>
                <form action="{% url 'store:abone_ol' %}" method="get">

                    <div class="form-row mb-2">
                        <div class="col-12">
                            <label class="h6 font-weight-normal d-none" for="exampleInputEmail3">Email</label>
                            <input type="email" value="{{ request.GET.email }}" class="form-control mb-2"
                                   placeholder="example@company.com" name="email" aria-label="Subscribe form"
                                   id="exampleInputEmail3" required>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block" data-loading-text="Sending">
                                <span>Abone ol</span>
                            </button>
                        </div>
                    </div>
                </form>
                <p class="text-gray font-small m-0">Bilgilerinizi Paylaşmayacağız <a class="text-black" href="#">Gizlilik</a>
                </p>
            </div>
        </div>
        <hr class="my-5">
        <div class="row">
            <div class="col">

                <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                    <p class="font-weight-normal font-small mb-0">Copyright ©
                        <span class="current-year"><script>document.write(new Date().getFullYear())</script></span>. Tüm
                        Hakları saklıdır.
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/include/js.html
{% load static %}
<!-- Core -->
<script src="{% static '/vendor/jquery/dist/jquery-3.7.1.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/popper.js/dist/umd/popper.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/bootstrap/dist/js/bootstrap.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/headroom.js/dist/headroom.min.js' %}?{% now 'U' %}"></script>

<!-- Vendor JS -->
<script src="{% static '/vendor/onscreen/dist/on-screen.umd.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/nouislider/distribute/nouislider.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/waypoints/lib/jquery.waypoints.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/jarallax/dist/jarallax.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/jquery.counterup/jquery.counterup.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/jquery-countdown/dist/jquery.countdown.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}?{% now 'U' %}"></script>
<script src="{% static '/vendor/prismjs/prism.js' %}"></script>
<script src="{% static '/vendor/jquery-hitcount/jquery.postcsrf.js' %}?{% now 'U' %}"></script>
<script src="{% static 'django_ckeditor_5/dist/bundle.js' %}?{% now 'U' %}"></script>

<script async defer="defer" src="https://buttons.github.io/buttons.js"></script><!-- Neumorphism JS -->

<script type="module" src="https://unpkg.com/@dotlottie/player-component@1.0.0/dist/dotlottie-player.js"></script>

<!-- Neumorphism JS -->
<script src="{% static 'js/neumorphism.js' %}?{% now 'U' %}"></script>

<script src="{% static 'vendor/jquery.blueimp-gallery.min.js' %}?{% now 'U' %}"></script>

<script>
    blueimp.Gallery(document.getElementById('links').getElementsByTagName('a'), {
        container: '#blueimp-gallery-carousel',
        carousel: true
    })
</script>

<script>
    var data = {
        title: 'JavaScript Templates',
        license: {
            name: 'MIT license',
            url: 'https://opensource.org/licenses/MIT'
        },
        features: ['lightweight & fast', 'powerful', 'zero dependencies']
    }
</script>

<script>
    var fullscreenOptions = {
        // Defines if the gallery should open in fullscreen mode:
        fullscreen: false
    }
</script>

templates/include/logout.html
<form action="{% url "logout" %}" method="post">
    {% csrf_token %}
    <li>
        <button class="dropdown-item animate-hover" type="submit"><span
                class="fa fa-sign-out mr-2 text-danger text-small animate-right-2"></span>Çıkış
        </button>
    </li>
</form>

templates/include/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible shadow-soft fade show"
                 role="alert">
        {% else %}
            <div class="alert alert-{{ message.tags }} alert-dismissible shadow-soft fade show"
                 role="alert">
        {% endif %}

        <span class="alert-inner--icon">
                                    {% if message.tags == 'error' %}
                                        <span class="far fa-thumbs-down"></span>
                                    {% elif message.tags == 'success' %}
                                        <span class="far fa-thumbs-up"></span>
                                    {% else %}

                                    {% endif %}
                                </span>

        <span class="alert-inner--text"><strong>{{ message }}</strong> </span>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    {% endfor %}
</div>

{% endif %}

templates/include/paginator.html
<!-- Pagination -->
<div class="d-flex justify-content-center w-100">
    <div class="mt-5">
        <nav aria-label="Blog page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" aria-label="ilk sayfa" title="ilk sayfa"
                           href="?page=1">
                            <span class="fas fa-angle-double-left"></span>
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link rounded" aria-label="önceki sayfa"
                           title="önceki sayfa"
                           href="?page={{ page_obj.previous_page_number }}">
                            <span class="fas fa-angle-left"></span>
                        </a>
                    </li>

                {% endif %}
                {% for number in page_obj.paginator.page_range %}
                    {% if page_obj.number == number %}
                        <li class="page-item active">
                            <a class="page-link" href="#">{{ number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ number }}">{{ number }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link rounded" aria-label="first link"
                           title="sonraki sayfa"
                           href="?page={{ page_obj.next_page_number }}">
                            <span class="fas fa-angle-right"></span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" aria-label="first link" title="son sayfa"
                           href="?page={{ page_obj.paginator.num_pages }}">
                            <span class="fas fa-angle-double-right"></span>
                        </a>
                    </li>

                {% else %}
                    <li class="page-item">
                        <a class="page-link" aria-label="first link"
                           href="#">
                            <span class="fas fa-angle-double-right"></span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

templates/include/search.html
<form method="get">
    <div class="input-group justify-content-lg-start mx-auto"
         style="-moz-border-radius:20px; -webkit-border-radius:20px; border-radius:20px;">
        {% if 'makale' in request.path %}
            <input class="form-control" title="Arama Çubuğu" data-toggle="tooltip"
                   placeholder="Kategori veya Başlık"
                   type="text" name="search" value="{{ request.GET.search }}"
                   style="-moz-border-radius: 20px; -webkit-border-radius: 20px; border-radius: 20px;">
        {% else %}
            <input class="form-control" title="Arama Çubuğu" data-toggle="tooltip"
                   placeholder="Kategori, Başlık veya Marka"
                   type="text" name="search" value="{{ request.GET.search }}"
                   style="-moz-border-radius: 20px; -webkit-border-radius: 20px; border-radius: 20px;">
        {% endif %}

    </div>
</form>